### ISSUE TITLE
error when extracting

### ISSUE THREAD

**Issue by Groovii** [sgossner/VSCO-2-CE#10]
Hi, imwriting this because i really wanna use this in my projects in fl studo, but theres a problem: whenever i try to extract the files, it keeps saying "Please insert the last disk of the multi-volume set and click OK to continue" but when i click OK, the same error keeps popping up, and when i click cancel, a new window pops up that says that the zip folder is empty, and it also says "Before you can extract files, you must copy files to this compressed (Zipped) folder." i need help, i really wanna use this but windows isnt letting me.

**Comment by sgossner** [comment]
Did you try downloading from the Dropbox mirror?
https://www.dropbox.com/s/p2p6whunwekb9s1/VSCO-2-CE-1.1.0.zip?dl=0

Make sure the download truly completes. It sounds like you did not finish downloading the files, which can happen because of a connection issue. It should be about 2.14 GB, so if the .zip is smaller than that, it is not done and you must re-download.

Alternately, consider trying the Virtual Playing Orchestra; it is based on VSCO 2 CE but also adds instruments from several other free libraries too. It is also in SFZ format:
http://virtualplaying.com/
