### ISSUE TITLE
Sfz Volume

### ISSUE THREAD

**Issue by isolin** [sgossner/VSCO-2-CE#13]
Hi, I'm writing my own toy sampler from scratch with a very basic support of sfz. VSCO-CE is a really awesome base to start with, thank you very much for making it public. Looking at the sfz files included in this project I got all the basic op codes up and running, but I am wondering about the meaning of `volume`.

The [specs](https://sfzformat.com/opcodes/volume) state that it represents the volume in dB usually in the range of -144 to +6. All values I saw in this project are positive and most of them are larger than +6. When I'm looking at the `volume` in relation to the `velocity` I rather suspect it is somehow relative, but not sure to what base. So I am really confused about the meaning of `volume`.

I would be grateful if someone could please explain me how to apply `volume` to the samples to make them sound as the authors intended to.

**Comment by sgossner** [comment]
You should consider joining the SFZ Discord group to answer questions like this; I am not an expert on SFZ by any stretch. You can find a link and very thorough documentation of all SFZ opcodes on the SFZ wiki:
https://sfzformat.com/

The main SFZ player used today is Sforzando, which has the most complete implementation available (albeit almost no 'Cakewalk' opcodes implemented). Sforzando/ARIA Engine allows volume ranges far, far above +6 dB. This is practical purpose...

Volume is used primarily to compensate for non-normalized samples, to allow a smooth gradation in dynamic levels. Volume is a flat gain added to the sample BEFORE the velocity-based attenuation curve is applied. For example, if you have two samples, one at approximately -1 dB and another averaging around -7 dB, but the second one is mapped lower, at the transition point there will be 6 dB of difference between the two, and the lower velocity will be noticeably too quiet. By adding 6 dB with Volume to the lower sample, it will compensate for that difference and thus when you transition from one to the other the change will be far less jarring. You can even under- or over- compensate depending on taste and preferences to create a more or less dynamic/responsive instrument feel.

It can also be used, for example, to set the volume of release or 'noise' samples like breath, piano pedal, key strike, or other mechanical noises at a fixed amount relative to the 'normal' sample for an appropriate blend, especially in conjunction with CC's.

If you instead normalize samples, no alteration is needed, but then you usually lose your dynamic variation across the instrument from the normalization, and you also have to deal with people accidentally playing those samples too loud and complaining about noise because a sample which is supposed to be played at -40 dB is played at -1 dB instead.

Velocity simply assigns a sample to only play given a range of valid midi velocity values. The actual attenuation curve is controlled separately, such as with amp_veltrack.

**Comment by sgossner** [comment]
By the way, there is a test suite of test .sfz files you can run here to see if your sampler is running to spec/interpreting files correctly:
https://github.com/sfz/tests/

**Comment by isolin** [comment]
Thank you very much for the explanation. It ultimately helped me to get the volumes in my sampler right. I asked here, because I felt it is a question specific to the VSCO instruments and their volume values.
