### ISSUE TITLE
String set has hardcoded absolute paths

### ISSUE THREAD

**Issue by refi64** [sgossner/VSCO-2-CE#2]
![vs](https://cloud.githubusercontent.com/assets/1690697/20199672/e2cb6144-a771-11e6-9dc9-d42942e99a21.png)

**Comment by sgossner** [comment]
These combination patches aren't intended for Sforzando and will probably only work in ARIA, as they require a multi-timbral instrument to function. Regardless, working on addressing the paths issue now, thanks!

**Comment by sgossner** [comment]
So far things are not looking good for relative paths... it appears only official libraries can be designated as relative paths, so for now it may require every user to manually write the absolute path in the ariax files (editable in any text editor, and not very hard to do, just majorly inconvenient). I will see if I can find a workaround, but it will probably require someone far more experienced with xml than myself.
http://www.plogue.com/phpBB3/viewtopic.php?f=34&t=7681&p=41198&hilit=ariax#p41198

**Comment by Disar** [comment]
> These combination patches aren't intended for Sforzando and will probably only work in ARIA,

Sforzando runs on Aria engine tho? But yes the ariax files only seem to load the first slot rather than the whole set.

**Comment by sgossner** [comment]
> Sforzando runs on Aria engine tho? But yes the ariax files only seem to load the first slot rather than the whole set.

Because confusion is key when creating products, the ARIA engine and ARIA Player are two different things yet both are often referred to in shorthand just as 'ARIA' (although typically meaning Player)- indeed, the two can even be updated or downgraded independently of each other!

The .ariax files preserve the settings of all 16 slots (one instrument per slot) in the instance of ARIA Player at the moment they are created.

Sforzando is basically a monotimbral, stripped-down version of the ARIA Player. Yes, it might load the .ariax, but because it is monotimbral, it cannot load more than one .sfz at a time.

**Comment by Disar** [comment]
Ah, didn't realize the ARIA player was a separate thing. It's a shame it's monotrimbral. There is so much potential with a product they promote as an "open standard".

**Comment by sgossner** [comment]
Tell me about it! 

SFZ is very poorly documented and heavily forked as each company which uses it has added their own opcodes and extended functionality (collectively these are called 'SFZ 2.0'), with just three different lists of opcodes which barely explain anything and only a handful of examples available online. Not to mention last I knew, owned by Cakewalk, which shut down, and now has re-opened under new ownership!

There is no public documentation for working with the ARIA engine-specific features or GUI aside from a few posts on their forum (I assume if one were to license ARIA to distribute with the library, there might be some decent SDK/documentation for that), and no one has created a good GUI-based editor for SFZ, unlike SF2, which despite being very outdated, has several quite solid GUI-based editors.

Honestly, I understand why Plogue wants to keep ARIA set aside to license to developers (a similar process is used for all other samplers in some way or another), but because SFZ is so open and hackable, not to mention the ARIA engine, despite being quite solid, is still no replacement for the likes of Kontakt, I don't see any commercial developers rushing to use it... so it all kind of sits there, some half-forgotten pet project of Garritan and Plogue. Perhaps if they sold ARIA to folks wanting more out of their SFZ collections for like $50 or something, it would get more attention?

**Comment by Disar** [comment]
Only editor I found was [this](http://mildon.me/sfzdesigner)

Im just using all this to waste time, so spending money isn't really on my priority list.
But like you said it makes more sense to provide a better player for a small price tag. Or no price tag at all considering they being proud of it being an open standard...eh

LinuxSampler seems to have many feature sets missing, so I guess that wont be worth it either.

**Comment by sgossner** [comment]
> Only editor I found was this

It's not bad, but it's very slow to work in, only suitable for little projects.

I actually ended up having someone custom program an automapper in Java for me, which I used to make these SFZ files (then a little manual tweaking). If you're interested in the process, the SFZ automapper (or "Folder-to-SFZ Converter") is available for free from our website. I use it regularly to test-build patches of our professional instruments, up to 3,000 samples, and the thing hardly blinks so long as the naming conventions are done right. I keep planning to build onto it more, but never find the time or rationale for the cost of hiring a programmer to do the work (one of the problems with being a company developing non-open-source freeware, like Sforzando).

I filmed part of the process of making the SFZ's using the automapper-
https://www.youtube.com/watch?v=cMJuQbZAf5Q

> Or no price tag at all considering they being proud of it being an open standard...eh

Like I said, they don't really own the standard, so no matter how proud they are of it, I doubt they'd be willing to put their 'professional'-level sampler in the public domain or any other freeware option. Plogue is a company, ARIA Player is a product, no doubt one which cost tens [[edit: or hundreds]] of thousands to develop. I may be proud of putting the 3,000 samples of VSCO 2 CE into the public domain, but I wouldn't be willing to put the 60,000+ samples of VSCO 2 Pro into the public domain. Regardless, I'm happy to argue that how they have made that product viable is not the method I would have chosen if market saturation was of any interest.

> LinuxSampler seems to have many feature sets missing, so I guess that wont be worth it either.

As far as I am aware, LinuxSampler isn't all that bad. It seems to have all the important parts of the SFZ spec covered, although it perhaps isn't as robust as Sforzando.

The 'rising star' in samplers is one called HISE. It is still very much in development, but some developers are suggesting it may be the 'Kontakt killer'. It's free last I knew, so if you want something to play around in, that might be your ticket. I believe SFZ import was at least planned.
