### ISSUE TITLE
Zip file download is corrupt

### ISSUE THREAD

**Issue by dtangres** [sgossner/VSCO-2-CE#6]
When I try and download the Community Edition collection of instruments as a zip file, I find that I cannot unzip it, since the computer tells me the archive is corrupt.

**Comment by sgossner** [comment]
Hi, try the download again. Note that GitHub zips up the file for you- there's absolutely nothing that can be done from this end to "fix" this. It's most likely a corruption that occurred while downloading- when files get over 1 GB, the likelihood of a ZIP failing increases. This might be due to anything from a lag spike to slow internet. If you experience an unreliable or unsteady internet connection, I recommend going to an internet cafe or nearby campus, which often provide reliable internet.

If it fails again or a third time, you can also try installing GitHub Desktop and pressing the "Download to Desktop" button instead- note that you may need to sign up for GitHub to do this (it's all free).

**Comment by j1j2c** [comment]
I have the same issue  (using Windows 10). I have downloaded the zip file more than 10 times, using 3 different browsers and the same thing happens each time. If this is a GitHub problem, surely there must be some way you can put the zip file on the project webpage rather than forcing us to download it from GitHub, which doesn't seem to work

**Comment by sgossner** [comment]
Try this download instead-
https://github.com/sgossner/VSCO-2-CE/releases/tag/1.1.0

I used to host the .zip file via S3, but it became extremely costly to do so and there were a lot of issues with people having wrong versions and far more download issues there too. This way everything is in the open and can be easily updated, modified, or built upon.

**Comment by j1j2c** [comment]
In the meantime, I gave up on zip files, installed GitHub desktop and chose "open in desktop" that worked fine, so my advice to anyone with the same issue would be to do that :)

**Comment by sgossner** [comment]
> In the meantime, I gave up on zip files, installed GitHub desktop and chose "open in desktop" that worked fine, so my advice to anyone with the same issue would be to do that :)

Probably the best plan. If there are updates to CE in the future, you can just sync with Github and it'll download the updates for you. ;)

**Comment by jlagarespo** [comment]
Even easier, there is also no real need to open the repo in desktop, as you can just do it from the command line...

**Comment by sgossner** [comment]
> Even easier, there is also no real need to open the repo in desktop, as you can just do it from the command line...

Thanks for the suggestion, but keep in mind most computer users [running Mac and Windows] probably aren't comfortable using command line and would prefer a GUI even if it adds an extra step. That being said, if you wanted to write a description of how to do this, I'd be happy to add it to the readme for anyone else interested.

**Comment by UFOshnik** [comment]
wtf spam? error?

чт, 17 янв. 2019 г. в 22:18, Sam Gossner <notifications@github.com>:

**Comment by sgossner** [comment]
> wtf spam? error?

No idea, but somehow you subscribed to this issue. Click 'Unsubscribe' as instructed in the e-mail or above to the right of the thread under 'Notifications'.

**Comment by jlagarespo** [comment]
``git clone https://github.com/sgossner/VSCO-2-CE.git``
If you are using windows, just install the git from the official installer and the architecture your system is using. If you are using any linux distro GNOME based just do ``sudo apt install git`` (you may need some privielegies to do this.) If you are though, using any xfce distro just install it with pacman. Nad if you are using mac, or any BSD based system, just install homebrew.
