### ISSUE TITLE
BrassQuartet.ariax doesn't work

### ISSUE THREAD

**Issue by JonatasBeque** [sgossner/VSCO-2-CE#7]
Hi!

When I try to load the file BrassQuartet.ariax in Sforzando, it shows the error below:

Please. is it possible to fix this issue?

![image](https://user-images.githubusercontent.com/36718879/36515752-b0360ee2-1759-11e8-8d9b-9fbfba5cd5bf.png)

**Comment by sgossner** [comment]
Please read 'How To Install.txt', your question is answered there quite thoroughly!
https://github.com/sgossner/VSCO-2-CE/blob/SFZ/How%20To%20Install.txt

Basically it's Plogue's fault- they don't want "unofficial libraries" made in ARIA so they force all ariax presets that aren't licensed to use what are called Fixed Paths, meaning it links to the specific locations of the instruments on the hard drive, rather than the more logical Relative Paths, which are exactly what they sound like they are. There is nothing I can do to make this easier- the ONLY way to use the ariax is to manually edit them in a text editor as instructed. All you have to do is change the fixed path so it is correct for your system.

**Comment by SeleDreams** [comment]
> Please read 'How To Install.txt', your question is answered there quite thoroughly! https://github.com/sgossner/VSCO-2-CE/blob/SFZ/How%20To%20Install.txt
> 
> Basically it's Plogue's fault- they don't want "unofficial libraries" made in ARIA so they force all ariax presets that aren't licensed to use what are called Fixed Paths, meaning it links to the specific locations of the instruments on the hard drive, rather than the more logical Relative Paths, which are exactly what they sound like they are. There is nothing I can do to make this easier- the ONLY way to use the ariax is to manually edit them in a text editor as instructed. All you have to do is change the fixed path so it is correct for your system.

Kind of a late comment however as it still arrives first on google's search results, I do feel like I need to correct it.
Even if we do that, that actually will *not* work if we use sforzando. As while it will find the sfz file's location, sforzando is a single slot sfz player it just cannot read the ensemble patches. it will only load the first instrument of the patch.
It will also fail to load the reverb defined by the preset as it is not available in sforzando.

**Comment by sgossner** [comment]
> Kind of a late comment however as it still arrives first on google's search results, I do feel like I need to correct it. Even if we do that, that actually will _not_ work if we use sforzando. As while it will find the sfz file's location, sforzando is a single slot sfz player it just cannot read the ensemble patches. it will only load the first instrument of the patch. It will also fail to load the reverb defined by the preset as it is not available in sforzando.

Thank you for the note. .ariax files can only be used in ARIA Player (a multi-timbral derivative of Sforzando made under license for MakeMusic), which is also freely available online. Hence the extension ".ariax". Sforzando (mono-timbral) uses its own presets system called 'Snapshots' which are completely different.

Making presets work in Sforzando would be completely useless because, as you note, it is mono-timbral and thus it is not possible to load multiple patches at once. Instead Sforzando users should load up separate instances of Sforzando for each patch they wish to use. .ariax files are only the concern of ARIA users and should be ignored by Sforzando users.

MakeMusic are shutting down Finale but appear to be keeping Garritan alive though with little in the way of new products, so it is uncertain how long ARIA will continue to be available.

https://makemusic.zendesk.com/hc/en-us/sections/7141874221463-ARIA-Player-Installers
